### ISSUE TITLE
Is it possible to get the source files ready to import to denodo locally?

### ISSUE THREAD

**Issue by Tato14** [denodo/denodocommunity-lab-environment#1]
Thanks for the great tool. Due to security issues, I cannot install neither docker or vm so I was wondering if I could get the db ready to upload to denodo and use them locally. Thanks

**Comment by denodo-community** [comment]
Most of the data are stored as plain [CSV files](https://github.com/denodo/denodocommunity-lab-environment/tree/master/lab-environment-sources/res/db/data), and other [types of files](https://github.com/denodo/denodocommunity-lab-environment/tree/master/lab-environment-sources/res/files).

You could access to those files locally in you copy them to your server, but please note that in that case, as all the sources are plain files, you are not going to see the optimizations applied by Denodo when it is delegating the queries to the data sources.

For that reason we recommend to have access to the data sources, to simulate a real scenario.
